---
strict: true
site_name: stories
site_description: Define a user story in the business transaction DSL.
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: "https://raw.githubusercontent.com\
    /dry-python/brand/master/logo/dry-python.png"
  # FIXME: Favicon.
  language: 'en'
repo_name: dry-python/stories
repo_url: 'https://github.com/dry-python/stories'
edit_uri: ''
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - 'Home': index.md
  - 'Why': why.md
  - 'Definition': definition.md
  - 'Usage': usage.md
  - 'Execution': execution.md
  - 'Debugging': debugging.md
  - 'Composition': composition.md
  - 'Failure protocol': failure_protocol.md
  - 'Contrib':
      - 'Py.test': contrib/pytest.md
      - 'Debug toolbars': contrib/debug_toolbars.md
      - 'Sentry': contrib/sentry.md
  - 'FAQ': faq.md
  - 'Development': development.md
  - 'Changelog': changelog.md
  # A UI hack to split Table of Content into two visual parts.
  - '': '/'
  - '': '/'
  - '': '/'
  - '': '/'
  - '': '/'
  - 'GitHub': 'https://github.com/dry-python'
  - 'Twitter': 'https://twitter.com/dry_py'
  - 'Gitter': 'https://gitter.im/dry-python/stories'
  - 'LinkedIn': 'https://www.linkedin.com/company/drylabs/'
